// <auto-generated />
namespace EveTransactions.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddRecipes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRecipes));
        
        string IMigrationMetadata.Id
        {
            get { return "201501121321249_AddRecipes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
