// <auto-generated />
namespace EveTransactions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MaxRuns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaxRuns));
        
        string IMigrationMetadata.Id
        {
            get { return "201610261225519_MaxRuns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
